"""Geometry operations: WGS84 buffering, radius clipping, CRS reprojection, and
curb-line / corner-fillet construction from centerlines + widths.

WHY THIS IS A PACKAGE. It was one 2,195-line module holding six unrelated jobs, and the one
everyone actually needed - the leg frame, (station, offset) - was in the middle of it. Split by
the QUESTION each part answers:

    crs           what datum is this in, and how do I clip a radius in it
    leg_frame     where is this, in station-along-the-leg and offset-from-it
    traced_kerbs  what can be made of a surveyor's traced kerb, and when to refuse it
    corners       the fillet at each corner, and the pavement ring they close
    stripes       the shape of the paint: strips, tapers, stalls, post rows, hatching
    context       the street's surroundings - an estimated crossing, the sidewalk band

The layering is crs | leg_frame <- traced_kerbs <- corners, and leg_frame <- stripes, context.
There are no cycles, which is worth stating because the old module had no way to show that.

EVERY PUBLIC NAME IS RE-EXPORTED HERE. `from src.geometry.model import X` is done in 30 modules
and ~470 places reach a leg's centerline through it; an import site should not have to know
which file a function landed in.
"""
from src.geometry.model.crs import (NJ_STATE_PLANE_FT, WGS84, buffer_point_wgs84, clip_to_radius,
                                    label_quadrants,
                                    nearest_per_quadrant,
                                    reproject_to_state_plane,
                                    split_leg_centerlines)
from src.geometry.model.leg_frame import (Leg, NORTH_SOUTH_LEG_TOLERANCE, STRIP_SAMPLE_FT,
                                          band_from_offsets,
                                          curb_edge_by_station,
                                          curb_offsets_at_stations,
                                          curb_point_at_station,
                                          curb_station_span,
                                          frame_at,
                                          inset_line_ft,
                                          inset_point_at_station,
                                          kerb_inset_offsets,
                                          kerb_parallel_line_ft,
                                          kerb_referenced_band_polygon,
                                          leg_bearing_deg,
                                          leg_clearance_ft,
                                          line_direction,
                                          line_from_offsets,
                                          narrowest_half_width_ft,
                                          offset_band_polygon,
                                          paint_stations,
                                          place_in_measured_frame,
                                          point_at,
                                          points_at_offset_ft,
                                          polyline_frame,
                                          side_facing,
                                          station_offset,
                                          station_offset_many,
                                          unit_vector,
                                          vertex_tangents)
from src.geometry.model.traced_kerbs import (CORNER_BLEND_FT, CURB_EXTRAPOLATION_MAX_SLOPE,
                                             CURB_EXTRAPOLATION_MIN_BASELINE_FT,
                                             CURB_POINT_BEHIND_PENALTY,
                                             CURB_POINT_BEHIND_TOLERANCE_FT,
                                             CURB_POINT_CORNER_ZONE_FT,
                                             CURB_POINT_MAX_SKEW_DEG,
                                             CURB_POINT_MAX_WIDTH_RATIO,
                                             CURB_POINT_MIN_WIDTH_RATIO,
                                             MAX_ARC_FIT_RESIDUAL_FT,
                                             MAX_KERB_FIT_RESIDUAL_FT,
                                             MIN_KERB_ARC_SWEEP_DEG,
                                             PLAUSIBLE_CORNER_RADIUS_FT,
                                             SMOOTHED_ARC_POINTS,
                                             assign_curb_points_to_legs,
                                             assign_kerbs_to_corners,
                                             corner_radii_from_kerbs,
                                             curb_line_from_points,
                                             fit_circle_ft,
                                             kerb_radius_is_usable,
                                             smooth_traced_arc,
                                             traced_corner_arc,
                                             traced_corner_join,
                                             trimmed_curb_lines)
from src.geometry.model.corners import (THROUGH_STREET_ANGLE_DEG, build_corner_fillets,
                                        build_pavement_polygon,
                                        corner_apron_annulus,
                                        corner_overlay_polygon,
                                        fillet_curb_corner,
                                        is_through_street,
                                        through_street_sides)
from src.geometry.model.stripes import (BULBOUT_TAPER_RATE, MIN_HATCH_STROKE_FT,
                                        bollard_points_ft,
                                        clip_paint_clear_of,
                                        curb_extension_line,
                                        curbside_strip_polygon,
                                        hatch_lines_ft,
                                        lane_narrowing_edge_lines_ft,
                                        lane_narrowing_polygons_ft,
                                        lane_narrowing_taper_ft,
                                        lane_narrowing_taper_polygons_ft,
                                        parking_lane_edge_line_ft,
                                        parking_stall_count_ft,
                                        parking_stall_lines_ft)
from src.geometry.model.context import (CROSSWALK_OFFSET_FROM_KERB_FT, CROSS_STREET_MAX_ANGLE_DEG,
                                        SIDEWALK_PROBE_DISTANCES_FT,
                                        SIDEWALK_PROBE_REACH_FT,
                                        crosswalk_estimate_ft,
                                        sidewalk_span_ft)

__all__ = [
                                    "BULBOUT_TAPER_RATE",
                                    "CORNER_BLEND_FT",
                                    "CROSSWALK_OFFSET_FROM_KERB_FT",
                                    "CROSS_STREET_MAX_ANGLE_DEG",
                                    "CURB_EXTRAPOLATION_MAX_SLOPE",
                                    "CURB_EXTRAPOLATION_MIN_BASELINE_FT",
                                    "CURB_POINT_BEHIND_PENALTY",
                                    "CURB_POINT_BEHIND_TOLERANCE_FT",
                                    "CURB_POINT_CORNER_ZONE_FT",
                                    "CURB_POINT_MAX_SKEW_DEG",
                                    "CURB_POINT_MAX_WIDTH_RATIO",
                                    "CURB_POINT_MIN_WIDTH_RATIO",
                                    "MAX_ARC_FIT_RESIDUAL_FT",
                                    "MAX_KERB_FIT_RESIDUAL_FT",
                                    "MIN_HATCH_STROKE_FT",
                                    "MIN_KERB_ARC_SWEEP_DEG",
                                    "NJ_STATE_PLANE_FT",
                                    "NORTH_SOUTH_LEG_TOLERANCE",
                                    "PLAUSIBLE_CORNER_RADIUS_FT",
                                    "SIDEWALK_PROBE_DISTANCES_FT",
                                    "SIDEWALK_PROBE_REACH_FT",
                                    "SMOOTHED_ARC_POINTS",
                                    "STRIP_SAMPLE_FT",
                                    "THROUGH_STREET_ANGLE_DEG",
                                    "WGS84",
                                    "Leg",
                                    "assign_curb_points_to_legs",
                                    "assign_kerbs_to_corners",
                                    "band_from_offsets",
                                    "bollard_points_ft",
                                    "buffer_point_wgs84",
                                    "build_corner_fillets",
                                    "build_pavement_polygon",
                                    "clip_paint_clear_of",
                                    "clip_to_radius",
                                    "corner_apron_annulus",
                                    "corner_overlay_polygon",
                                    "corner_radii_from_kerbs",
                                    "crosswalk_estimate_ft",
                                    "curb_edge_by_station",
                                    "curb_extension_line",
                                    "curb_line_from_points",
                                    "curb_offsets_at_stations",
                                    "curb_point_at_station",
                                    "curb_station_span",
                                    "curbside_strip_polygon",
                                    "fillet_curb_corner",
                                    "fit_circle_ft",
                                    "frame_at",
                                    "hatch_lines_ft",
                                    "inset_line_ft",
                                    "inset_point_at_station",
                                    "is_through_street",
                                    "kerb_inset_offsets",
                                    "kerb_parallel_line_ft",
                                    "kerb_radius_is_usable",
                                    "kerb_referenced_band_polygon",
                                    "label_quadrants",
                                    "lane_narrowing_edge_lines_ft",
                                    "lane_narrowing_polygons_ft",
                                    "lane_narrowing_taper_ft",
                                    "lane_narrowing_taper_polygons_ft",
                                    "leg_bearing_deg",
                                    "leg_clearance_ft",
                                    "line_direction",
                                    "line_from_offsets",
                                    "narrowest_half_width_ft",
                                    "nearest_per_quadrant",
                                    "offset_band_polygon",
                                    "paint_stations",
                                    "parking_lane_edge_line_ft",
                                    "parking_stall_count_ft",
                                    "parking_stall_lines_ft",
                                    "place_in_measured_frame",
                                    "point_at",
                                    "points_at_offset_ft",
                                    "polyline_frame",
                                    "reproject_to_state_plane",
                                    "side_facing",
                                    "sidewalk_span_ft",
                                    "smooth_traced_arc",
                                    "split_leg_centerlines",
                                    "station_offset",
                                    "station_offset_many",
                                    "through_street_sides",
                                    "traced_corner_arc",
                                    "traced_corner_join",
                                    "trimmed_curb_lines",
                                    "unit_vector",
                                    "vertex_tangents",
]
